defaults:
  run:
    working-directory: ./master_frontend_lemoncode\modulo5_UnitTesting\ejercicio-unit-testing\src

name: CI Workflow

on: push

jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Tests
        run: npm test